name: SyphlexSkyblock
author: iDurpy
main: net.syphlex.skyblock.Skyblock
version: 0.0.5b
api-version: 1.13

depend:
  - PlaceholderAPI
  - DecentHolograms

dependencies:
  server:
    PlaceholderAPI:
      # Load order is relative to the dependency. So here PlaceholderAPI loads before our plugin.
      load: BEFORE
      required: true
    DecentHolograms:
      load: BEFORE
      required: true

commands:
  island:
    aliases: [is]
  mine:
    aliases: [mines]
  minion:
    aliases: [minions]