name: SyphlexSkyblock
author: iDurpy
main: net.syphlex.skyblock.Skyblock
version: 2.1.0-BETA
api-version: 1.13

softdepend:
  - PlaceholderAPI
  - WildStacker

depend:
  - Vault

dependencies:
  server:
    PlaceholderAPI:
      # Load order is relative to the dependency. So here PlaceholderAPI loads before our plugin.
      load: BEFORE
      required: true
    NBTAPI:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: true

commands:
  syphlexskyblock:
  island:
    aliases: [is]
  mine:
    aliases: [mines]